<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Event;

class SampleEventsSeeder extends Seeder
{
    public function run(): void
    {
        $events = [
            // ── Upcoming Events ──────────────────────────────────────────────
            ['title' => 'Web Development For Beginners', 'category' => 'Computer Science', 'date' => '2026-01-26', 'time_display' => '6:00 PM - 8:00 PM', 'location' => 'Online', 'participants' => 245, 'description' => 'Learn the fundamentals of web development in this beginner-friendly workshop.', 'image_key' => 'EngageWebDevBG', 'tab' => 'Upcoming Events'],
            ['title' => 'Stocks, Funds & Investment', 'category' => 'Finance', 'date' => '2026-01-20', 'time_display' => 'Tue, Thu & Fri, 6:00 PM - 7:00 PM', 'location' => 'Online', 'participants' => 178, 'description' => '10 sessions comprehensive course on stocks, funds, and investment strategies.', 'image_key' => 'StocksBG', 'tab' => 'Upcoming Events'],
            ['title' => 'Swimming 101 for Adults', 'category' => 'Sports & Wellness', 'date' => '2026-01-20', 'time_display' => 'Tue & Thu 5:00 PM, Sat 1:30 PM', 'location' => 'ADDU Aquatic Center', 'participants' => 89, 'description' => '10 sessions comprehensive swimming program for adults. Learn basic techniques.', 'image_key' => 'Swim101', 'tab' => 'Upcoming Events'],
            ['title' => 'Fundamentals of Digital Marketing', 'category' => 'Marketing', 'date' => '2026-01-21', 'time_display' => 'Mon, Wed & Fri, 6:00 PM - 8:00 PM', 'location' => 'Online', 'participants' => 156, 'description' => '4 sessions course covering the fundamentals of digital marketing.', 'image_key' => 'DigitalMarket', 'tab' => 'Upcoming Events'],
            ['title' => 'Design Thinking Workshop', 'category' => 'Innovation & Design', 'date' => '2026-01-24', 'time_display' => 'Saturday, 9:00 AM - 11:00 AM', 'location' => 'Online', 'participants' => 198, 'description' => '8 sessions workshop on design thinking — human-centered innovation.', 'image_key' => 'DesignThinkBG', 'tab' => 'Upcoming Events'],
            ['title' => 'Executive Leadership Training', 'category' => 'Leadership', 'date' => '2026-01-26', 'time_display' => 'Mon, Wed & Thu, 6:00 PM - 8:00 PM', 'location' => 'Online', 'participants' => 132, 'description' => '12 sessions comprehensive leadership training program.', 'image_key' => 'LeadershipBG', 'tab' => 'Upcoming Events'],

            // ── Past Events ──────────────────────────────────────────────────
            ['title' => 'Christmas Alumni Reunion 2025', 'category' => 'Social Event', 'date' => '2025-12-20', 'time_display' => '6:00 PM - 10:00 PM', 'location' => 'ADDU Gymnasium', 'participants' => 423, 'description' => 'A festive celebration bringing together alumni for fellowship, dinner, and holiday cheer.', 'image_key' => 'ChristmasReunion', 'tab' => 'Past Events'],
            ['title' => 'Data Science & Analytics Workshop', 'category' => 'Professional Dev', 'date' => '2025-11-15', 'time_display' => '1:00 PM - 6:00 PM', 'location' => 'ADDU Computer Lab', 'participants' => 87, 'description' => 'Hands-on workshop covering Python, data visualization, and machine learning basics.', 'image_key' => 'DataSciBG', 'tab' => 'Past Events'],
            ['title' => 'Alumni Career Fair 2025', 'category' => 'Career', 'date' => '2025-10-28', 'time_display' => '9:00 AM - 5:00 PM', 'location' => 'ADDU Covered Court', 'participants' => 542, 'description' => 'Major job fair featuring 50+ companies actively recruiting ADDU alumni across all levels.', 'image_key' => 'CareerFairBG', 'tab' => 'Past Events'],
            ['title' => 'Alumni Golf Tournament', 'category' => 'Sports', 'date' => '2025-09-22', 'time_display' => '6:00 AM - 2:00 PM', 'location' => 'Apo Golf & Country Club', 'participants' => 76, 'description' => 'Annual charity golf tournament with proceeds supporting ADDU scholarship programs.', 'image_key' => 'GolfTournaBG', 'tab' => 'Past Events'],
            ['title' => 'Leadership Summit: Future of Work', 'category' => 'Professional Dev', 'date' => '2025-07-20', 'time_display' => '2:00 PM - 7:00 PM', 'location' => 'Virtual Event', 'participants' => 234, 'description' => 'Panel discussions on remote work, digital transformation, and emerging career trends.', 'image_key' => 'LeaderSummitBG', 'tab' => 'Past Events'],

            // ── Teaching Opportunities ───────────────────────────────────────
            ['title' => 'Guest Lecturer - Digital Marketing', 'category' => 'Business', 'date' => '1 Semester', 'time_display' => 'Tue & Thu preferred', 'location' => 'School of Business and Governance', 'participants' => 8, 'compensation' => 'Honorarium provided', 'description' => 'Share your expertise in digital marketing with our business students.', 'image_key' => 'GuestLectureBG', 'tab' => 'Teaching Opportunities', 'posted_by' => 'Dr. Antonio Reyes'],
            ['title' => 'Workshop Facilitator - Python', 'category' => 'Computer Science', 'date' => '2 Days', 'time_display' => 'March 8-9, 2026', 'location' => 'Department of Computer Science', 'participants' => 15, 'compensation' => 'Php 15,000', 'description' => 'Conduct hands-on Python workshop for intermediate students.', 'image_key' => 'WorkshopBG', 'tab' => 'Teaching Opportunities', 'posted_by' => 'Prof. Maria Santos'],
            ['title' => 'Mentor - Engineering Capstone', 'category' => 'Engineering', 'date' => '1 Academic Year', 'time_display' => '4 hours/month', 'location' => 'College of Engineering', 'participants' => 12, 'compensation' => 'Certificate + Recognition', 'description' => 'Guide senior engineering students through their capstone projects.', 'image_key' => 'MentorCapBG', 'tab' => 'Teaching Opportunities', 'posted_by' => 'Engr. Robert Tan'],
            ['title' => 'Adjunct Professor - Finance', 'category' => 'Finance', 'date' => '1 Semester', 'time_display' => 'MWF 2:00 PM - 3:30 PM', 'location' => 'School of Business and Governance', 'participants' => 6, 'compensation' => 'Competitive academic rate', 'description' => 'Teach undergraduate financial management course.', 'image_key' => 'FinancialManageBG', 'tab' => 'Teaching Opportunities', 'posted_by' => 'Dean Patricia Cruz'],
            ['title' => 'Guest Speaker - Nursing', 'category' => 'Nursing', 'date' => '2-hour Session', 'time_display' => 'Feb 25, 2026 at 3:00 PM', 'location' => 'School of Nursing', 'participants' => 4, 'compensation' => 'Honorarium + Travel', 'description' => 'Share insights on healthcare administration with nursing students.', 'image_key' => 'HealthCareBG', 'tab' => 'Teaching Opportunities', 'posted_by' => 'Dr. Elizabeth Gomez'],
            ['title' => 'Workshop Leader - UX/UI', 'category' => 'IT', 'date' => '5 Days Intensive', 'time_display' => 'April 14-18, 9:00 AM', 'location' => 'Dept. of Information Technology', 'participants' => 11, 'compensation' => 'Php 50,000', 'description' => 'Lead intensive UX/UI bootcamp covering research and prototyping.', 'image_key' => 'WorkshopLeadBG', 'tab' => 'Teaching Opportunities', 'posted_by' => 'Prof. Jennifer Lim'],
            ['title' => 'Career Advisor - Law', 'category' => 'Law', 'date' => 'Ongoing', 'time_display' => '2 hours/week', 'location' => 'College of Law', 'participants' => 7, 'compensation' => 'Volunteer (Recognition)', 'description' => 'Provide career guidance to law students preparing for bar exams.', 'image_key' => 'CareerAdviceBG', 'tab' => 'Teaching Opportunities', 'posted_by' => 'Atty. Marco Gonzales'],
            ['title' => 'Lab Instructor - Data Science', 'category' => 'Mathematics', 'date' => '1 Semester', 'time_display' => 'Saturdays 10:00 AM', 'location' => 'Department of Mathematics', 'participants' => 9, 'compensation' => 'Standard adjunct rate', 'description' => 'Supervise data science lab sessions using R and Python.', 'image_key' => 'LabInstructBG', 'tab' => 'Teaching Opportunities', 'posted_by' => 'Dr. Thomas Valdez'],
            ['title' => 'Skills Workshop - Speaking', 'category' => 'Communication', 'date' => '3-hour Workshop', 'time_display' => 'March 12, 2026', 'location' => 'Department of Communication', 'participants' => 13, 'compensation' => 'Php 8,000', 'description' => 'Teach students effective public speaking and presentation techniques.', 'image_key' => 'SkillWorkshopBG', 'tab' => 'Teaching Opportunities', 'posted_by' => 'Prof. Amanda Reyes'],
            ['title' => 'Practicum Supervisor', 'category' => 'Accounting', 'date' => '6 months', 'time_display' => 'Monthly check-ins', 'location' => 'School of Business', 'participants' => 5, 'compensation' => 'Certificate + Recognition', 'description' => 'Supervise accounting students during their industry practicum.', 'image_key' => 'AccountingBG', 'tab' => 'Teaching Opportunities', 'posted_by' => 'CPA Catherine Velasco'],

            // ── Seminars & Workshops ─────────────────────────────────────────
            ['title' => 'Leadership in the Digital Age', 'category' => 'Professional Dev', 'date' => '2026-03-15', 'time_display' => '9:00 AM - 4:00 PM', 'location' => 'ADDU Finster Hall', 'participants' => 120, 'description' => 'Leading teams in a digital-first environment with focus on remote management.', 'image_key' => 'LeaderDigitalBG', 'tab' => 'Seminars & Workshops'],
            ['title' => 'Advanced Financial Analytics', 'category' => 'Finance', 'date' => '2026-04-05', 'time_display' => '1:00 PM - 5:00 PM', 'location' => 'Virtual / Zoom', 'participants' => 85, 'description' => 'Master financial modeling and data analytics for modern investment strategies.', 'image_key' => 'AdvFinanceBG', 'tab' => 'Seminars & Workshops'],
            ['title' => 'AI and Machine Learning', 'category' => 'Technology', 'date' => '2026-04-12', 'time_display' => '10:00 AM - 12:00 PM', 'location' => 'ADDU Community Center', 'participants' => 45, 'description' => 'Strategic overview of AI capabilities for business implementations.', 'image_key' => 'AIandMachineBG', 'tab' => 'Seminars & Workshops'],
            ['title' => 'Agile Project Management', 'category' => 'Management', 'date' => '2026-05-20', 'time_display' => '9:00 AM - 3:00 PM', 'location' => 'Online', 'participants' => 200, 'description' => 'Certification-ready workshop for Agile and Scrum methodologies.', 'image_key' => 'ProjectManagementBG', 'tab' => 'Seminars & Workshops'],
            ['title' => 'Legal Issues in E-Commerce', 'category' => 'Law', 'date' => '2026-06-10', 'time_display' => '2:00 PM - 5:00 PM', 'location' => 'ADDU College of Law', 'participants' => 60, 'description' => 'Deep dive into digital trade, consumer rights, and data privacy frameworks.', 'image_key' => 'LegalLawBG', 'tab' => 'Seminars & Workshops'],
            ['title' => 'Entrepreneurship Mastery', 'category' => 'Business', 'date' => '2026-06-15', 'time_display' => '9:00 AM - 5:00 PM', 'location' => 'Online', 'participants' => 110, 'description' => 'Scale your startup with expert insights on operations and funding.', 'image_key' => 'EntrepBG', 'tab' => 'Seminars & Workshops'],
            ['title' => 'Workplace Mental Health', 'category' => 'Wellness', 'date' => '2026-07-02', 'time_display' => '1:30 PM - 4:30 PM', 'location' => 'Virtual', 'participants' => 150, 'description' => 'Promoting psychological safety and mental well-being in corporate settings.', 'image_key' => 'MentalHealthBG', 'tab' => 'Seminars & Workshops'],
            ['title' => 'Modern Content Marketing', 'category' => 'Marketing', 'date' => '2026-07-20', 'time_display' => '10:00 AM - 3:00 PM', 'location' => 'ADDU Arrupe Hall', 'participants' => 95, 'description' => 'Storytelling and content strategies for the social media era.', 'image_key' => 'MarketingBG', 'tab' => 'Seminars & Workshops'],
            ['title' => 'Cybersecurity Essentials', 'category' => 'IT Security', 'date' => '2026-08-05', 'time_display' => '9:00 AM - 12:00 PM', 'location' => 'Online', 'participants' => 180, 'description' => 'Protecting business data from modern threats and social engineering.', 'image_key' => 'CybersecBG', 'tab' => 'Seminars & Workshops'],
            ['title' => 'Sustainable Business', 'category' => 'Innovation', 'date' => '2026-08-18', 'time_display' => '1:00 PM - 4:00 PM', 'location' => 'ADDU Community Center', 'participants' => 70, 'description' => 'Integrating ESG principles into your business strategy and operations.', 'image_key' => 'SustainBG', 'tab' => 'Seminars & Workshops'],
            ['title' => 'Excel for Business Pros', 'category' => 'Data', 'date' => '2026-09-03', 'time_display' => '9:00 AM - 12:00 PM', 'location' => 'Online', 'participants' => 300, 'description' => 'Advanced functions, pivot tables, and data visualization techniques.', 'image_key' => 'ExcelBG', 'tab' => 'Seminars & Workshops'],
            ['title' => 'Pharmacy Trends 2026', 'category' => 'Healthcare', 'date' => '2026-09-15', 'time_display' => '2:00 PM - 5:00 PM', 'location' => 'ADDU School of Nursing', 'participants' => 55, 'description' => 'Updating clinical knowledge on emerging pharmaceuticals and patient care.', 'image_key' => 'PharmaBG', 'tab' => 'Seminars & Workshops'],
        ];

        foreach ($events as $data) {
            Event::create(array_merge([
                'posted_by'    => null,
                'compensation' => null,
                'status'       => null,
                'submitted_by' => null,
                'submitted_by_email' => null,
            ], $data));
        }

        echo "Sample events seeded: " . count($events) . " events created.\n";
    }
}
